services:
  gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: oracle }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
