doctrine:
    dbal:
        default_connection: oracle
        connections:
            oracle:
                driver: 'oci8'
                dbname: 'othergkn'
                user: 'othergkn'
                # password: 'othergkn'
                # host: '10.52.138.32'
                # port: '1521'
                # service: true
                # servicename: 'R52GZK0'
                charset: utf8
                url: '%env(resolve:DATABASE_URL)%'
                schema_filter: /^(NORM_MIGR_VER|NORM_BLOCK|NORM_PROCESS)/
        # configure these for your database server

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        default_entity_manager: oracle_em
        entity_managers:
            oracle_em:
                connection: oracle
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    tree:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
        #default_entity_manager: oracle
        #entity_managers:
        #    oracle:
        #        connection: oracle

services:
    oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }