knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: '@KnpMenu/menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: true
    # the renderer to use, list is also available by default
    default_renderer: twig


services:
  app.menu_builder:
    class: App\Menu\MenuBuilder
    arguments: ["@knp_menu.factory", '@App\Repository\MenuRepository']
    tags:
      - { name: knp_menu.menu_builder, method: mainMenu, alias: main }

