-- Doctrine Migration File Generated on 2019-10-03 08:08:24

-- Version 20191002051448
CREATE SEQUENCE SEQ_NORM_BLOCK_ID START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NORM_PROCESS_ID START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE TABLE NORM_BLOCK (ID NUMBER NOT NULL, UNIQUE INDEX PK_NORM_BLOCK_ID (id), PRIMARY KEY(id));
COMMENT ON COLUMN NORM_BLOCK.ID IS 'id';
CREATE TABLE NORM_PROCESS (ID NUMBER NOT NULL, PARENT_ID NUMBER DEFAULT NULL NULL, ID_NORM_BLOCK NUMBER DEFAULT NULL NULL, NOTE VARCHAR2(1000, UNIQUE INDEX PK_NORM_PROCESS_ID (id),PRIMARY KEY(id)) DEFAULT NULL NULL);
CREATE INDEX i_norm_process_parent_id ON NORM_PROCESS (PARENT_ID);
CREATE INDEX i_norm_process_block_id ON NORM_PROCESS (ID_NORM_BLOCK);
INSERT INTO norm_migr_ver (version, executed_at) VALUES ('20191002051448', CURRENT_TIMESTAMP);
