-- Doctrine Migration File Generated on 2019-11-06 05:43:42

-- Version 20191106053045
CREATE TABLE NORM_OBJECT (ID NUMBER NOT NULL, CAD_NUM VARCHAR2(100) DEFAULT NULL NULL, REG_ID NUMBER DEFAULT NULL NULL, PRIMARY KEY(ID));
CREATE TABLE NORM_ERR_SLT (ID NUMBER NOT NULL, OBJ_ID NUMBER NOT NULL, BLOCK_ID NUMBER NOT NULL, VALUES CLOB DEFAULT NULL NULL, PRIMARY KEY(ID));
COMMENT ON COLUMN "NORM_ERR_SLT".VALUES IS '(DC2Type:json)';
INSERT INTO norm_migr_ver (version, executed_at) VALUES ('20191106053045', CURRENT_TIMESTAMP);
